version: '3.8'

services:
  nginx:
    container_name: 2131-nginx
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "8000:80"
    working_dir: /var/www/app-2131
    volumes:
      - ./:/var/www/app-2131
      - ./docker/nginx/:/etc/nginx/conf.d/
  php:
    container_name: 2131-php
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    working_dir: /var/www/app-2131
    volumes:
      - .:/var/www/app-2131
      - /var/www/app-2131/vendor
  postgres:
    container_name: 2131-postgres
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - ./docker/postgres/database:/var/lib/postgresql/data
      - ./docker/postgres/dumps/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/postgres/dumps:/dumps
      - ./docker/postgres/scripts:/scripts